# Data Cleaning Case — Pedidos Comerciais

## Objetivo

Limpar, validar e padronizar a planilha `pedidos_sujos.xlsx`, preservando os dados recuperáveis e documentando as decisões tomadas.

**Regra do case:** não alterar silenciosamente um valor ambíguo. Quando uma correção não puder ser inferida com segurança, sinalize ou mantenha como ausente.

## 1. Importar bibliotecas e carregar os dados

Carregue a planilha a partir de `../data/raw/pedidos_sujos.xlsx`.

**Funções/métodos úteis:**
- `import pandas as pd`
- `pd.read_excel()`
- `.head()`
- `.shape`
- `.columns`

In [2]:
import pandas as pd

df = pd.read_excel('../data/raw/pedidos_sujos.xlsx')

In [3]:
df.head()

,pedido_id,data_pedido,cliente,email,categoria,produto,quantidade,preco_unitario,desconto_pct,cidade,estado,status
0,PED-1001,2026-05-18,Daniel Almeida,daniel.almeida@email.com,Acessórios,Suporte para notebook,2.0,99,0%,Porto Alegre,RS,pago
1,PED-1002,14/05/2026,Renata Gomes,renata.gomes@email.com,Escritório,Caneta gel,2.0,8.5,0%,Criciúma,SC,pago
2,PED-1003,46201,Juliana Barbosa,juliana.barbosa@email.com,Escritório,Caderno A5,4.0,24.9,0,Florianópolis,SC,Entregue
3,PED-1004,46151,Bruno Dias,bruno.dias@email.com,Informática,Mouse sem fio,4.0,79.9,0,São Paulo,SP,Enviado
4,NaN,46162,Eduardo Oliveira,eduardo.oliveira@email.com,Casa,Garrafa térmica,1.0,69,0,Florianópolis,SC,Enviado

In [4]:
df.columns

Index(['pedido_id', 'data_pedido', 'cliente', 'email', 'categoria', 'produto',
       'quantidade', 'preco_unitario', 'desconto_pct', 'cidade', 'estado',
       'status'],
      dtype='object')

In [5]:
df.shape

(184, 12)

## 2. Fazer uma inspeção inicial

Descubra:
- número de linhas e colunas;
- tipos inferidos;
- quantidade de valores ausentes;
- número de linhas duplicadas;
- valores distintos nas colunas categóricas.

**Funções/métodos úteis:**
- `.info()`
- `.dtypes`
- `.isna().sum()`
- `.duplicated().sum()`
- `.value_counts(dropna=False)`
- `.nunique()`

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pedido_id       183 non-null    object
 1   data_pedido     184 non-null    object
 2   cliente         184 non-null    object
 3   email           174 non-null    object
 4   categoria       184 non-null    object
 5   produto         184 non-null    object
 6   quantidade      183 non-null    float64
 7   preco_unitario  183 non-null    object
 8   desconto_pct    180 non-null    object
 9   cidade          184 non-null    object
 10  estado          184 non-null    object
 11  status          184 non-null    object
dtypes: float64(1), object(11)
memory usage: 17.4+ KB

In [7]:
df.isna().sum()

pedido_id          1
data_pedido        0
cliente            0
email             10
categoria          0
produto            0
quantidade         1
preco_unitario     1
desconto_pct       4
cidade             0
estado             0
status             0
dtype: int64

In [8]:
df.duplicated().sum()

4

In [9]:
df.value_counts(dropna=False)

pedido_id  data_pedido  cliente           email                       categoria    produto                quantidade  preco_unitario  desconto_pct  cidade          estado  status
PED-1047   46169        Ana Almeida       ana.almeida@email.com       Escritório   Organizador de mesa    2.0         54,90           10            Curitiba        PR      PAGO        2
PED-1102   46200        Igor Barbosa       igor.barbosa@email.com     informatica  Webcam HD              2.0          189.00         5%            Florianópolis   SC      PENDENTE    2
PED-1013   46263        Vanessa Almeida   vanessa.almeida@email.com   Acessórios   Cabo USB-C             6.0         34.9            0             Porto Alegre    RS      ENVIADO     2
PED-1149   46166        Marina Oliveira   marina.oliveira@email.com   Escritório   Caneta gel             6.0         8.5             10            Criciúma        SC      Entregue    2
PED-1126   46153        Vanessa Lima      vanessa.lima@email.com      Acessórios   Suporte para notebook  4.0         99              15            São Paulo       SP      pendente    1
                                                                                                                                                                                       ..
PED-1065   31/02/2026   Thiago Pereira     thiago.pereira@email.com   Casa         Extensão elétrica      6.0         R$ 39,90        10            Tubarão         SC      Enviado     1
PED-1066   46187        Marina Ferreira   marina.ferreira@email.com   Acessórios   Suporte para notebook  3.0         99              0             Tubarão         SC      Enviado     1
PED-1067   22/08/2026   Sofia Almeida     sofia.almeida@email.com     Escritório   Caneta gel             1.0         8.5             0             Curitiba        PR      Pago        1
PED-1068   46190        Paulo Gomes       paulo.gomes@email.com       Informática  Webcam HD              6.0         189             5             Belo Horizonte  MG      Pendente    1
NaN        46162        Eduardo Oliveira  eduardo.oliveira@email.com  Casa         Garrafa térmica        1.0         69              0             Florianópolis   SC      Enviado     1
Length: 180, dtype: int64

In [10]:
df.nunique()

pedido_id         179
data_pedido       127
cliente           140
email             132
categoria          15
produto            18
quantidade          7
preco_unitario     30
desconto_pct        9
cidade             14
estado             13
status             19
dtype: int64

## 3. Remover duplicatas exatas

Identifique registros inteiramente duplicados e mantenha apenas uma ocorrência.

Antes de remover, registre quantas duplicatas existem.

**Funções/métodos úteis:**
- `.duplicated()`
- `.drop_duplicates()`
- `.copy()`

In [11]:
df[df.duplicated(keep=False)]

,pedido_id,data_pedido,cliente,email,categoria,produto,quantidade,preco_unitario,desconto_pct,cidade,estado,status
12,PED-1013,46263,Vanessa Almeida,vanessa.almeida@email.com,Acessórios,Cabo USB-C,6.0,34.9,0,Porto Alegre,RS,ENVIADO
13,PED-1013,46263,Vanessa Almeida,vanessa.almeida@email.com,Acessórios,Cabo USB-C,6.0,34.9,0,Porto Alegre,RS,ENVIADO
47,PED-1047,46169,Ana Almeida,ana.almeida@email.com,Escritório,Organizador de mesa,2.0,"54,90",10,Curitiba,PR,PAGO
48,PED-1047,46169,Ana Almeida,ana.almeida@email.com,Escritório,Organizador de mesa,2.0,"54,90",10,Curitiba,PR,PAGO
103,PED-1102,46200,Igor Barbosa,igor.barbosa@email.com,informatica,Webcam HD,2.0,189.00,5%,Florianópolis,SC,PENDENTE
104,PED-1102,46200,Igor Barbosa,igor.barbosa@email.com,informatica,Webcam HD,2.0,189.00,5%,Florianópolis,SC,PENDENTE
151,PED-1149,46166,Marina Oliveira,marina.oliveira@email.com,Escritório,Caneta gel,6.0,8.5,10,Criciúma,SC,Entregue
152,PED-1149,46166,Marina Oliveira,marina.oliveira@email.com,Escritório,Caneta gel,6.0,8.5,10,Criciúma,SC,Entregue

In [12]:
df_clean = df.drop_duplicates().copy()
df_clean.duplicated().sum()

0

In [13]:
# 1. ID ausente
ids_ausentes = df_clean["pedido_id"].isna()

# 2. ID duplicado
ids_duplicados = df_clean["pedido_id"].duplicated(keep=False) & df_clean["pedido_id"].notna()

In [14]:
df_clean.loc[
    ids_ausentes | ids_duplicados,
    ["pedido_id", "cliente", "data_pedido"]
]

  pedido_id           cliente data_pedido
4       NaN  Eduardo Oliveira       46162

## 4. Normalizar campos de texto

Padronize espaços em branco e capitalização quando apropriado.

Observe especialmente:
- `cliente`
- `email`
- `categoria`
- `produto`
- `cidade`
- `estado`
- `status`

Não aplique a mesma transformação cegamente a todas as colunas.

**Funções/métodos úteis:**
- `.astype("string")`
- `.str.strip()`
- `.str.lower()`
- `.str.upper()`
- `.str.title()`
- `.replace()`

In [15]:
df_clean.head()

,pedido_id,data_pedido,cliente,email,categoria,produto,quantidade,preco_unitario,desconto_pct,cidade,estado,status
0,PED-1001,2026-05-18,Daniel Almeida,daniel.almeida@email.com,Acessórios,Suporte para notebook,2.0,99,0%,Porto Alegre,RS,pago
1,PED-1002,14/05/2026,Renata Gomes,renata.gomes@email.com,Escritório,Caneta gel,2.0,8.5,0%,Criciúma,SC,pago
2,PED-1003,46201,Juliana Barbosa,juliana.barbosa@email.com,Escritório,Caderno A5,4.0,24.9,0,Florianópolis,SC,Entregue
3,PED-1004,46151,Bruno Dias,bruno.dias@email.com,Informática,Mouse sem fio,4.0,79.9,0,São Paulo,SP,Enviado
4,NaN,46162,Eduardo Oliveira,eduardo.oliveira@email.com,Casa,Garrafa térmica,1.0,69,0,Florianópolis,SC,Enviado

In [16]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 180 entries, 0 to 183
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pedido_id       179 non-null    object
 1   data_pedido     180 non-null    object
 2   cliente         180 non-null    object
 3   email           170 non-null    object
 4   categoria       180 non-null    object
 5   produto         180 non-null    object
 6   quantidade      179 non-null    float64
 7   preco_unitario  179 non-null    object
 8   desconto_pct    176 non-null    object
 9   cidade          180 non-null    object
 10  estado          180 non-null    object
 11  status          180 non-null    object
dtypes: float64(1), object(11)
memory usage: 18.3+ KB

In [17]:
df_clean[["cliente","email","produto","categoria","cidade","estado","status"]]=df_clean[["cliente","email","produto","categoria","cidade","estado","status"]].astype("string")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pedido_id       183 non-null    object
 1   data_pedido     184 non-null    object
 2   cliente         184 non-null    object
 3   email           174 non-null    object
 4   categoria       184 non-null    object
 5   produto         184 non-null    object
 6   quantidade      183 non-null    float64
 7   preco_unitario  183 non-null    object
 8   desconto_pct    180 non-null    object
 9   cidade          184 non-null    object
 10  estado          184 non-null    object
 11  status          184 non-null    object
dtypes: float64(1), object(11)
memory usage: 17.4+ KB

In [18]:
df_clean["cliente"]=df_clean["cliente"].str.title()
df_clean.head()

,pedido_id,data_pedido,cliente,email,categoria,produto,quantidade,preco_unitario,desconto_pct,cidade,estado,status
0,PED-1001,2026-05-18,Daniel Almeida,daniel.almeida@email.com,Acessórios,Suporte para notebook,2.0,99,0%,Porto Alegre,RS,pago
1,PED-1002,14/05/2026,Renata Gomes,renata.gomes@email.com,Escritório,Caneta gel,2.0,8.5,0%,Criciúma,SC,pago
2,PED-1003,46201,Juliana Barbosa,juliana.barbosa@email.com,Escritório,Caderno A5,4.0,24.9,0,Florianópolis,SC,Entregue
3,PED-1004,46151,Bruno Dias,bruno.dias@email.com,Informática,Mouse sem fio,4.0,79.9,0,São Paulo,SP,Enviado
4,NaN,46162,Eduardo Oliveira,eduardo.oliveira@email.com,Casa,Garrafa térmica,1.0,69,0,Florianópolis,SC,Enviado

In [19]:
df_clean["categoria"]=df_clean["categoria"].str.title()
df_clean["categoria"]=df_clean["categoria"].str.strip()
df_clean["categoria"].head(20)

0      Acessórios
1      Escritório
2      Escritório
3     Informática
4            Casa
5      Acessórios
6            Casa
7      Escritório
8            Casa
9      Escritório
10    Informática
11     Escritorio
12     Acessórios
14     Escritório
15           Casa
16     Escritório
17    Informática
18    Informática
19     Acessórios
20     Acessórios
Name: categoria, dtype: string

In [20]:
df_clean["status"]=df_clean["status"].str.title()
df_clean["status"]=df_clean["status"].str.strip()

In [21]:
df_clean["cidade"] = df_clean["cidade"].str.strip().str.title()

In [22]:
df_clean["estado"] = df_clean["estado"].str.strip().str.upper()

In [23]:
df_clean.head(10)

,pedido_id,data_pedido,cliente,email,categoria,produto,quantidade,preco_unitario,desconto_pct,cidade,estado,status
0,PED-1001,2026-05-18,Daniel Almeida,daniel.almeida@email.com,Acessórios,Suporte para notebook,2.0,99,0%,Porto Alegre,RS,Pago
1,PED-1002,14/05/2026,Renata Gomes,renata.gomes@email.com,Escritório,Caneta gel,2.0,8.5,0%,Criciúma,SC,Pago
2,PED-1003,46201,Juliana Barbosa,juliana.barbosa@email.com,Escritório,Caderno A5,4.0,24.9,0,Florianópolis,SC,Entregue
3,PED-1004,46151,Bruno Dias,bruno.dias@email.com,Informática,Mouse sem fio,4.0,79.9,0,São Paulo,SP,Enviado
4,NaN,46162,Eduardo Oliveira,eduardo.oliveira@email.com,Casa,Garrafa térmica,1.0,69,0,Florianópolis,SC,Enviado
5,PED-1006,04/07/2026,Sofia Almeida,sofia.almeida@email.com,Acessórios,Suporte para notebook,5.0,99,0,Porto Alegre,RS,Pago
6,PED-1007,46159,Carla Santos,carla.santos@email.com,Casa,Garrafa térmica,5.0,69,0,Florianópolis,SC,Cancelado
7,PED-1008,46223,Helena Pereira,helena.pereira@email.com,Escritório,Caderno A5,1.0,24.9,15,Tubarão,SC,Pago
8,PED-1009,46225,Renata Lima,renata.lima@email.com,Casa,Garrafa térmica,6.0,"R$ 69,00",15,Tubarão,SC,Pago
9,PED-1010,46204,Ana Barbosa,ana.barbosa@email.com,Escritório,Caderno A5,0.0,24.9,5,Criciúma,SC,Enviado

## 5. Padronizar categorias

Verifique se grafias diferentes representam a mesma categoria ou status e converta-as para uma representação canônica.

Sugestão: construa um pequeno mapeamento explícito em vez de depender apenas de capitalização.

**Funções/métodos úteis:**
- `.unique()`
- `.value_counts()`
- `.replace({...})`
- `.map()`

In [24]:
df_clean["categoria"].unique()

<StringArray>
[ 'Acessórios',  'Escritório', 'Informática',        'Casa',  'Escritorio',
 'Informatica',  'Acessorios']
Length: 7, dtype: string

In [25]:
df_clean["categoria"] = df_clean["categoria"].replace({
    "Informatica": "Informática",
    "Escritorio": "Escritório",
    "Acessorios": "Acessórios"
})
df_clean["categoria"].unique()

<StringArray>
['Acessórios', 'Escritório', 'Informática', 'Casa']
Length: 4, dtype: string

In [26]:
df_clean["status"].unique()

<StringArray>
['Pago', 'Entregue', 'Enviado', 'Cancelado', 'Pendente']
Length: 5, dtype: string

## 6. Converter e validar datas

Converta `data_pedido` para um tipo de data consistente.

Existe pelo menos um valor que não representa uma data válida. Não force uma correção sem evidência.

**Funções/métodos úteis:**
- `pd.to_datetime()`
- parâmetro `errors="coerce"`
- parâmetro `dayfirst=True`
- `.isna()`

In [27]:
datas_raw = df_clean["data_pedido"].copy()
datas_numericas = pd.to_numeric(datas_raw, errors="coerce")
mask_excel = datas_numericas.notna()
df_clean.loc[mask_excel, ["pedido_id", "data_pedido"]].head(10)

   pedido_id data_pedido
2   PED-1003       46201
3   PED-1004       46151
4        NaN       46162
6   PED-1007       46159
7   PED-1008       46223
8   PED-1009       46225
9   PED-1010       46204
10  PED-1011       46163
12  PED-1013       46263
15  PED-1015       46162

In [28]:
datas_convertidas = pd.Series(
    pd.NaT,
    index=df_clean.index,
    dtype="datetime64[ns]"
)
datas_convertidas.loc[mask_excel] = pd.to_datetime(
    datas_numericas.loc[mask_excel],
    unit="D",
    origin="1899-12-30"
)
pd.DataFrame({
    "original": datas_raw[mask_excel].head(),
    "convertida": datas_convertidas[mask_excel].head()
})

  original convertida
2    46201 2026-06-28
3    46151 2026-05-09
4    46162 2026-05-20
6    46159 2026-05-17
7    46223 2026-07-20

In [36]:
mask_texto = ~mask_excel

datas_texto = (
    datas_raw.loc[mask_texto]
    .astype("string")
    .str.strip()
)

# Formato DD/MM/YYYY
datas_br_barra = pd.to_datetime(
    datas_texto,
    format="%d/%m/%Y",
    errors="coerce"
)

# Formato YYYY-MM-DD
datas_iso = pd.to_datetime(
    datas_texto,
    format="%Y-%m-%d",
    errors="coerce"
)

# Formato DD-MM-YYYY
datas_br_hifen = pd.to_datetime(
    datas_texto,
    format="%d-%m-%Y",
    errors="coerce"
)

# Formato DD/MM/YY
datas_br_curto = pd.to_datetime(
    datas_texto,
    format="%d/%m/%y",
    errors="coerce"
)

In [37]:
datas_texto_convertidas = (
    datas_br_barra
    .fillna(datas_iso)
    .fillna(datas_br_hifen)
    .fillna(datas_br_curto)
)

datas_convertidas.loc[mask_texto] = datas_texto_convertidas
df_clean["data_pedido"] = datas_convertidas

In [38]:
df_clean[df_clean["data_pedido"].dt.year == 1970][
    ["pedido_id", "data_pedido"]
]

Empty DataFrame
Columns: [pedido_id, data_pedido]
Index: []

In [39]:
df_datas_invalidas = pd.DataFrame({
    "pedido_id": df_clean["pedido_id"],
    "data_original": datas_raw,
    "data_convertida": df_clean["data_pedido"]
})

df_datas_invalidas[
    df_datas_invalidas["data_convertida"].isna()
]

   pedido_id data_original data_convertida
66  PED-1065    31/02/2026             NaT

In [41]:
df_clean[["pedido_id","data_pedido","cliente"]].head(10)

  pedido_id data_pedido           cliente
0  PED-1001  2026-05-18    Daniel Almeida
1  PED-1002  2026-05-14      Renata Gomes
2  PED-1003  2026-06-28   Juliana Barbosa
3  PED-1004  2026-05-09        Bruno Dias
4       NaN  2026-05-20  Eduardo Oliveira
5  PED-1006  2026-07-04     Sofia Almeida
6  PED-1007  2026-05-17      Carla Santos
7  PED-1008  2026-07-20    Helena Pereira
8  PED-1009  2026-07-22       Renata Lima
9  PED-1010  2026-07-01       Ana Barbosa

## 7. Converter campos numéricos

Trate:
- `quantidade`
- `preco_unitario`
- `desconto_pct`

A planilha mistura números reais e textos formatados.

Antes da conversão, talvez seja necessário remover símbolos, `%`, `R$`, separadores ou espaços.

**Funções/métodos úteis:**
- `.str.replace()`
- `pd.to_numeric()`
- `errors="coerce"`
- `.astype()`

**Atenção:** vírgula pode aparecer como separador decimal em alguns registros.

In [42]:
df_clean["preco_unitario"].unique()

array([99, 8.5, 24.9, 79.9, 69, 'R$ 69,00', '8,50', 34.9, 'R$ 8,50', 39.9,
       119.5, 54.9, 149.9, nan, '89,90', 189, 'R$ 99,00', '189,00', 89.9,
       '54,90', '69,00', 'R$ 39,90', '39,90', '149,90', ' 39.90 ',
       'R$ 24,90', ' 189.00 ', 'R$ 54,90', '79,90', ' 54.90 ', '34,90'],
      dtype=object)

In [43]:
preco_limpo = (
    df_clean["preco_unitario"]
    .astype("string")
    .str.strip()
    .str.replace("R$", "", regex=False)
    .str.replace(",", ".", regex=False)
)

preco_convertido = pd.to_numeric(preco_limpo, errors="coerce")

df_clean.loc[
    preco_convertido.isna(),
    ["pedido_id", "preco_unitario",]
]

   pedido_id preco_unitario
31  PED-1031            NaN

In [44]:
df_clean["preco_unitario"] = preco_convertido

In [45]:
df_clean["desconto_pct"].unique()

array(['0%', 0, 15, 5, 10, '15%', '5%', '10%', 'cinco', nan], dtype=object)

In [46]:
df_clean["desconto_pct"] = df_clean["desconto_pct"].replace({
    "0%": 0,
    "15%": 15,
    "5%": 5,
    "10%": 10,
    "cinco": 5
})
df_clean["desconto_pct"].unique()

array([ 0., 15.,  5., 10., nan])

In [47]:
df_clean["quantidade"].unique()

array([ 2.,  4.,  1.,  5.,  6.,  0.,  3., nan])

## 8. Validar regras básicas de negócio

Crie testes simples para detectar valores impossíveis ou suspeitos.

Exemplos:
- `quantidade` deve ser maior que zero;
- `preco_unitario` deve ser positivo;
- `desconto_pct` deve ficar em uma faixa plausível;
- `estado` deve ter formato consistente;
- `email` deve ter estrutura minimamente plausível.

**Funções/métodos úteis:**
- filtros booleanos;
- `.between()`
- `.isin()`
- `.str.contains()`
- `.str.match()`

Evite transformar este case em um validador completo de e-mail; basta uma checagem operacional simples.

In [49]:
ufs_validas = [
    "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO",
    "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI",
    "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"
]

df_clean[~df_clean["estado"].isin(ufs_validas)]

,pedido_id,data_pedido,cliente,email,categoria,produto,quantidade,preco_unitario,desconto_pct,cidade,estado,status
159,PED-1156,2026-06-03,Daniel Ferreira,<NA>,Acessórios,Cabo USB-C,4.0,34.9,0.0,Curitiba,XX,Cancelado

In [50]:
padrao_email = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

df_clean[
    ~df_clean["email"].str.match(padrao_email, na=False)
]

,pedido_id,data_pedido,cliente,email,categoria,produto,quantidade,preco_unitario,desconto_pct,cidade,estado,status
20,PED-1020,2026-06-01,Gabriel Santos,gabriel.santosemail.com,Acessórios,Suporte para notebook,4.0,99.0,5.0,Campinas,SP,Enviado
24,PED-1024,2026-08-05,Gabriel Martins,gabriel.martins@email.com,Escritório,Organizador de mesa,4.0,54.9,0.0,São Paulo,SP,Cancelado
26,PED-1026,2026-06-24,Daniel Silva,daniel.silva@email.com,Acessórios,Mochila compacta,3.0,149.9,10.0,Tubarão,SC,Entregue
32,PED-1032,2026-06-30,Fernanda Almeida,<NA>,Casa,Luminária LED,6.0,89.9,10.0,Belo Horizonte,MG,Entregue
35,PED-1035,2026-05-15,Bruno Martins,bruno.martins@email.com,Informática,Teclado USB,3.0,119.5,0.0,São Paulo,SP,Cancelado
36,PED-1036,2026-06-09,Ana Rocha,<NA>,Acessórios,Mochila compacta,6.0,149.9,0.0,Curitiba,PR,Pendente
42,PED-1042,2026-06-20,Marina Pereira,<NA>,Escritório,Caneta gel,1.0,8.5,15.0,Porto Alegre,RS,Entregue
45,PED-1045,2026-07-23,Helena Rocha,helena.rocha@email.com,Informática,Teclado USB,6.0,119.5,0.0,Belo Horizonte,MG,Cancelado
65,PED-1064,2026-05-01,Thiago Santos,<NA>,Informática,Webcam HD,4.0,189.0,10.0,Belo Horizonte,MG,Pago
66,PED-1065,NaT,Thiago Pereira,thiago.pereira@email.com,Casa,Extensão elétrica,6.0,39.9,10.0,Tubarão,SC,Enviado
85,PED-1084,2026-08-21,Bruno Lima,<NA>,Casa,Garrafa térmica,6.0,69.0,0.0,Criciúma,SC,Pago
96,PED-1095,2026-08-19,Gabriel Gomes,gabriel.gomesemail.com,Escritório,Organizador de mesa,1.0,54.9,10.0,Campinas,SP,Enviado
98,PED-1097,2026-07-19,Ana Dias,ana.dias@email.com,Casa,Extensão elétrica,3.0,39.9,NaN,Belo Horizonte,MG,Pendente
103,PED-1102,2026-06-27,Igor Barbosa,igor.barbosa@email.com,Informática,Webcam HD,2.0,189.0,5.0,Florianópolis,SC,Pendente
122,PED-1120,2026-05-03,Renata Gomes,renata.gomes@email.com,Casa,Extensão elétrica,4.0,39.9,0.0,Criciúma,SC,Pendente
127,PED-1125,2026-07-09,Helena Cardoso,helena.cardoso@email.com,Informática,Mouse sem fio,1.0,79.9,0.0,Campinas,SP,Entregue
130,PED-1128,2026-06-03,Marina Lima,<NA>,Casa,Extensão elétrica,6.0,39.9,0.0,Tubarão,SC,Enviado
133,PED-1131,2026-06-11,Thiago Oliveira,thiago.oliveiraemail.com,Casa,Garrafa térmica,5.0,69.0,10.0,São Paulo,SP,Cancelado
143,PED-1141,2026-06-25,Gabriel Cardoso,cliente@@email.com,Informática,Mouse sem fio,1.0,79.9,15.0,Campinas,SP,Enviado
145,PED-1143,2026-05-07,Paulo Almeida,paulo.almeida@email.com,Casa,Luminária LED,6.0,89.9,0.0,São Paulo,SP,Cancelado
148,PED-1146,2026-06-22,Helena Rocha,<NA>,Escritório,Caderno A5,3.0,24.9,NaN,Curitiba,PR,Pendente
157,PED-1154,2026-06-30,Renata Martins,renata.martins@email.com,Casa,Luminária LED,5.0,89.9,0.0,Florianópolis,SC,Enviado
158,PED-1155,2026-06-07,Igor Oliveira,<NA>,Escritório,Caderno A5,6.0,24.9,5.0,São Paulo,SP,Enviado
159,PED-1156,2026-06-03,Daniel Ferreira,<NA>,Acessórios,Cabo USB-C,4.0,34.9,0.0,Curitiba,XX,Cancelado
168,PED-1165,2026-07-06,Renata Rocha,<NA>,Acessórios,Suporte para notebook,4.0,99.0,0.0,Porto Alegre,RS,Pago
175,PED-1172,2026-06-06,Juliana Silva,juliana.silva@email.com,Acessórios,Cabo USB-C,5.0,34.9,0.0,Porto Alegre,RS,Cancelado

In [51]:
emails_ausentes = df_clean["email"].isna()

emails_invalidos = (
    df_clean["email"].notna()
    & ~df_clean["email"].str.match(padrao_email)
)

In [52]:
df_clean[emails_ausentes]

,pedido_id,data_pedido,cliente,email,categoria,produto,quantidade,preco_unitario,desconto_pct,cidade,estado,status
32,PED-1032,2026-06-30,Fernanda Almeida,<NA>,Casa,Luminária LED,6.0,89.9,10.0,Belo Horizonte,MG,Entregue
36,PED-1036,2026-06-09,Ana Rocha,<NA>,Acessórios,Mochila compacta,6.0,149.9,0.0,Curitiba,PR,Pendente
42,PED-1042,2026-06-20,Marina Pereira,<NA>,Escritório,Caneta gel,1.0,8.5,15.0,Porto Alegre,RS,Entregue
65,PED-1064,2026-05-01,Thiago Santos,<NA>,Informática,Webcam HD,4.0,189.0,10.0,Belo Horizonte,MG,Pago
85,PED-1084,2026-08-21,Bruno Lima,<NA>,Casa,Garrafa térmica,6.0,69.0,0.0,Criciúma,SC,Pago
130,PED-1128,2026-06-03,Marina Lima,<NA>,Casa,Extensão elétrica,6.0,39.9,0.0,Tubarão,SC,Enviado
148,PED-1146,2026-06-22,Helena Rocha,<NA>,Escritório,Caderno A5,3.0,24.9,NaN,Curitiba,PR,Pendente
158,PED-1155,2026-06-07,Igor Oliveira,<NA>,Escritório,Caderno A5,6.0,24.9,5.0,São Paulo,SP,Enviado
159,PED-1156,2026-06-03,Daniel Ferreira,<NA>,Acessórios,Cabo USB-C,4.0,34.9,0.0,Curitiba,XX,Cancelado
168,PED-1165,2026-07-06,Renata Rocha,<NA>,Acessórios,Suporte para notebook,4.0,99.0,0.0,Porto Alegre,RS,Pago

In [53]:
df_clean[emails_invalidos].sum()

<ipython-input-53-bc9c7824caae>:1: FutureWarning: The default value of numeric_only in DataFrame.sum is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_clean[emails_invalidos].sum()

pedido_id         PED-1020PED-1024PED-1026PED-1035PED-1045PED-10...
quantidade                                                     59.0
preco_unitario                                               1349.9
desconto_pct                                                   65.0
dtype: object

In [54]:
df_clean[df_clean["quantidade"] <= 0]

,pedido_id,data_pedido,cliente,email,categoria,produto,quantidade,preco_unitario,desconto_pct,cidade,estado,status
9,PED-1010,2026-07-01,Ana Barbosa,ana.barbosa@email.com,Escritório,Caderno A5,0.0,24.9,5.0,Criciúma,SC,Enviado
11,PED-1012,2026-07-22,Lucas Dias,lucas.dias@email.com,Escritório,Caneta gel,0.0,8.5,15.0,Campinas,SP,Entregue
183,PED-1180,2026-07-01,Renata Silva,renata.silva@email.com,Escritório,Organizador de mesa,0.0,54.9,15.0,Florianópolis,SC,Cancelado

In [55]:
df_clean[df_clean["preco_unitario"] <= 0]

Empty DataFrame
Columns: [pedido_id, data_pedido, cliente, email, categoria, produto, quantidade, preco_unitario, desconto_pct, cidade, estado, status]
Index: []

In [56]:
df_clean[~df_clean["desconto_pct"].between(0, 100)]

,pedido_id,data_pedido,cliente,email,categoria,produto,quantidade,preco_unitario,desconto_pct,cidade,estado,status
89,PED-1088,2026-05-17,Thiago Barbosa,thiago.barbosa@email.com,Casa,Extensão elétrica,1.0,39.9,NaN,Belo Horizonte,MG,Pendente
98,PED-1097,2026-07-19,Ana Dias,ana.dias@email.com,Casa,Extensão elétrica,3.0,39.9,NaN,Belo Horizonte,MG,Pendente
148,PED-1146,2026-06-22,Helena Rocha,<NA>,Escritório,Caderno A5,3.0,24.9,NaN,Curitiba,PR,Pendente
173,PED-1170,2026-05-25,Vanessa Martins,vanessa.martins@email.com,Casa,Garrafa térmica,3.0,69.0,NaN,Tubarão,SC,Entregue

In [57]:
# Emails ausentes
emails_ausentes = df_clean["email"].isna().sum()

# Emails inválidos, excluindo os ausentes
padrao_email = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

emails_invalidos = (
    df_clean["email"].notna()
    & ~df_clean["email"].str.match(padrao_email)
).sum()

# Estados inválidos
ufs_validas = [
    "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO",
    "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI",
    "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"
]

estados_invalidos = (~df_clean["estado"].isin(ufs_validas)).sum()

# Quantidades inválidas ou ausentes
quantidades_invalidas = (
    df_clean["quantidade"].isna()
    | (df_clean["quantidade"] <= 0)
).sum()

# Descontos ausentes
descontos_ausentes = df_clean["desconto_pct"].isna().sum()

# Preços ausentes ou inválidos
precos_invalidos = (
    df_clean["preco_unitario"].isna()
    | (df_clean["preco_unitario"] <= 0)
).sum()

In [58]:
resumo_validacao = {
    "Emails ausentes": emails_ausentes,
    "Emails inválidos": emails_invalidos,
    "Estados inválidos": estados_invalidos,
    "Quantidades inválidas": quantidades_invalidas,
    "Descontos ausentes": descontos_ausentes,
    "Preços inválidos": precos_invalidos
}

pd.Series(resumo_validacao)

Emails ausentes          10
Emails inválidos         16
Estados inválidos         1
Quantidades inválidas     4
Descontos ausentes        4
Preços inválidos          1
dtype: int64

## 9. Tratar valores ausentes e anomalias

Separe três situações:
1. valor que pode ser corrigido de forma determinística;
2. valor que deve permanecer ausente;
3. registro que merece ser sinalizado para revisão.

Não use `fillna()` indiscriminadamente.

**Funções/métodos úteis:**
- `.isna()`
- `.loc[]`
- `.fillna()` quando houver justificativa
- criação de uma coluna de controle, como `revisar`

In [59]:
padrao_email = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

emails_problematicos = (
    df_clean["email"].isna()
    | ~df_clean["email"].str.match(padrao_email, na=False)
)

estados_problematicos = ~df_clean["estado"].isin(ufs_validas)

quantidades_problematicas = (
    df_clean["quantidade"].isna()
    | (df_clean["quantidade"] <= 0)
)

precos_problematicos = (
    df_clean["preco_unitario"].isna()
    | (df_clean["preco_unitario"] <= 0)
)

descontos_problematicos = df_clean["desconto_pct"].isna()

datas_problematicas = df_clean["data_pedido"].isna()

In [60]:
df_clean["revisar"] = (
    emails_problematicos
    | estados_problematicos
    | quantidades_problematicas
    | precos_problematicos
    | descontos_problematicos
    | datas_problematicas
    | ids_ausentes
    | ids_duplicados
)

In [61]:
df_clean["revisar"].value_counts()

False    146
True      34
Name: revisar, dtype: Int64

In [62]:
df_clean["revisar"].sum()

34

In [63]:
df_clean[df_clean["revisar"]]

,pedido_id,data_pedido,cliente,email,categoria,produto,quantidade,preco_unitario,desconto_pct,cidade,estado,status,revisar
4,NaN,2026-05-20,Eduardo Oliveira,eduardo.oliveira@email.com,Casa,Garrafa térmica,1.0,69.0,0.0,Florianópolis,SC,Enviado,True
9,PED-1010,2026-07-01,Ana Barbosa,ana.barbosa@email.com,Escritório,Caderno A5,0.0,24.9,5.0,Criciúma,SC,Enviado,True
11,PED-1012,2026-07-22,Lucas Dias,lucas.dias@email.com,Escritório,Caneta gel,0.0,8.5,15.0,Campinas,SP,Entregue,True
20,PED-1020,2026-06-01,Gabriel Santos,gabriel.santosemail.com,Acessórios,Suporte para notebook,4.0,99.0,5.0,Campinas,SP,Enviado,True
24,PED-1024,2026-08-05,Gabriel Martins,gabriel.martins@email.com,Escritório,Organizador de mesa,4.0,54.9,0.0,São Paulo,SP,Cancelado,True
26,PED-1026,2026-06-24,Daniel Silva,daniel.silva@email.com,Acessórios,Mochila compacta,3.0,149.9,10.0,Tubarão,SC,Entregue,True
31,PED-1031,2026-08-10,Helena Barbosa,helena.barbosa@email.com,Casa,Extensão elétrica,5.0,NaN,10.0,Campinas,SP,Pendente,True
32,PED-1032,2026-06-30,Fernanda Almeida,<NA>,Casa,Luminária LED,6.0,89.9,10.0,Belo Horizonte,MG,Entregue,True
35,PED-1035,2026-05-15,Bruno Martins,bruno.martins@email.com,Informática,Teclado USB,3.0,119.5,0.0,São Paulo,SP,Cancelado,True
36,PED-1036,2026-06-09,Ana Rocha,<NA>,Acessórios,Mochila compacta,6.0,149.9,0.0,Curitiba,PR,Pendente,True
42,PED-1042,2026-06-20,Marina Pereira,<NA>,Escritório,Caneta gel,1.0,8.5,15.0,Porto Alegre,RS,Entregue,True
45,PED-1045,2026-07-23,Helena Rocha,helena.rocha@email.com,Informática,Teclado USB,6.0,119.5,0.0,Belo Horizonte,MG,Cancelado,True
65,PED-1064,2026-05-01,Thiago Santos,<NA>,Informática,Webcam HD,4.0,189.0,10.0,Belo Horizonte,MG,Pago,True
66,PED-1065,NaT,Thiago Pereira,thiago.pereira@email.com,Casa,Extensão elétrica,6.0,39.9,10.0,Tubarão,SC,Enviado,True
85,PED-1084,2026-08-21,Bruno Lima,<NA>,Casa,Garrafa térmica,6.0,69.0,0.0,Criciúma,SC,Pago,True
89,PED-1088,2026-05-17,Thiago Barbosa,thiago.barbosa@email.com,Casa,Extensão elétrica,1.0,39.9,NaN,Belo Horizonte,MG,Pendente,True
96,PED-1095,2026-08-19,Gabriel Gomes,gabriel.gomesemail.com,Escritório,Organizador de mesa,1.0,54.9,10.0,Campinas,SP,Enviado,True
98,PED-1097,2026-07-19,Ana Dias,ana.dias@email.com,Casa,Extensão elétrica,3.0,39.9,NaN,Belo Horizonte,MG,Pendente,True
103,PED-1102,2026-06-27,Igor Barbosa,igor.barbosa@email.com,Informática,Webcam HD,2.0,189.0,5.0,Florianópolis,SC,Pendente,True
119,PED-1117,2026-05-10,Carla Santos,carla.santos@email.com,Informática,Teclado USB,NaN,119.5,5.0,Tubarão,SC,Enviado,True
122,PED-1120,2026-05-03,Renata Gomes,renata.gomes@email.com,Casa,Extensão elétrica,4.0,39.9,0.0,Criciúma,SC,Pendente,True
127,PED-1125,2026-07-09,Helena Cardoso,helena.cardoso@email.com,Informática,Mouse sem fio,1.0,79.9,0.0,Campinas,SP,Entregue,True
130,PED-1128,2026-06-03,Marina Lima,<NA>,Casa,Extensão elétrica,6.0,39.9,0.0,Tubarão,SC,Enviado,True
133,PED-1131,2026-06-11,Thiago Oliveira,thiago.oliveiraemail.com,Casa,Garrafa térmica,5.0,69.0,10.0,São Paulo,SP,Cancelado,True
143,PED-1141,2026-06-25,Gabriel Cardoso,cliente@@email.com,Informática,Mouse sem fio,1.0,79.9,15.0,Campinas,SP,Enviado,True
145,PED-1143,2026-05-07,Paulo Almeida,paulo.almeida@email.com,Casa,Luminária LED,6.0,89.9,0.0,São Paulo,SP,Cancelado,True
148,PED-1146,2026-06-22,Helena Rocha,<NA>,Escritório,Caderno A5,3.0,24.9,NaN,Curitiba,PR,Pendente,True
157,PED-1154,2026-06-30,Renata Martins,renata.martins@email.com,Casa,Luminária LED,5.0,89.9,0.0,Florianópolis,SC,Enviado,True
158,PED-1155,2026-06-07,Igor Oliveira,<NA>,Escritório,Caderno A5,6.0,24.9,5.0,São Paulo,SP,Enviado,True
159,PED-1156,2026-06-03,Daniel Ferreira,<NA>,Acessórios,Cabo USB-C,4.0,34.9,0.0,Curitiba,XX,Cancelado,True
168,PED-1165,2026-07-06,Renata Rocha,<NA>,Acessórios,Suporte para notebook,4.0,99.0,0.0,Porto Alegre,RS,Pago,True
173,PED-1170,2026-05-25,Vanessa Martins,vanessa.martins@email.com,Casa,Garrafa térmica,3.0,69.0,NaN,Tubarão,SC,Entregue,True
175,PED-1172,2026-06-06,Juliana Silva,juliana.silva@email.com,Acessórios,Cabo USB-C,5.0,34.9,0.0,Porto Alegre,RS,Cancelado,True
183,PED-1180,2026-07-01,Renata Silva,renata.silva@email.com,Escritório,Organizador de mesa,0.0,54.9,15.0,Florianópolis,SC,Cancelado,True

In [77]:
df_clean["analise"] = ""

df_clean.loc[emails_problematicos, "analise"] += "email; "
df_clean.loc[estados_problematicos, "analise"] += "estado; "
df_clean.loc[quantidades_problematicas, "analise"] += "quantidade; "
df_clean.loc[precos_problematicos, "analise"] += "preco_unitario; "
df_clean.loc[descontos_problematicos, "analise"] += "desconto; "
df_clean.loc[datas_problematicas, "analise"] += "data; "
df_clean.loc[ids_ausentes, "analise"] += "pedido_id ausente; "
df_clean.loc[ids_duplicados, "analise"] += "pedido_id duplicado; "

df_clean["analise"] = df_clean["analise"].str.rstrip("; ")

In [78]:
df_clean.loc[
    df_clean["revisar"],
    ["pedido_id", "revisar", "analise"]
]

    pedido_id  revisar            analise
4         NaN     True  pedido_id ausente
9    PED-1010     True         quantidade
11   PED-1012     True         quantidade
20   PED-1020     True              email
24   PED-1024     True              email
26   PED-1026     True              email
31   PED-1031     True     preco_unitario
32   PED-1032     True              email
35   PED-1035     True              email
36   PED-1036     True              email
42   PED-1042     True              email
45   PED-1045     True              email
65   PED-1064     True              email
66   PED-1065     True        email; data
85   PED-1084     True              email
89   PED-1088     True           desconto
96   PED-1095     True              email
98   PED-1097     True    email; desconto
103  PED-1102     True              email
119  PED-1117     True         quantidade
122  PED-1120     True              email
127  PED-1125     True              email
130  PED-1128     True              email
133  PED-1131     True              email
143  PED-1141     True              email
145  PED-1143     True              email
148  PED-1146     True    email; desconto
157  PED-1154     True              email
158  PED-1155     True              email
159  PED-1156     True      email; estado
168  PED-1165     True              email
173  PED-1170     True           desconto
175  PED-1172     True              email
183  PED-1180     True         quantidade

In [79]:
df_clean.loc[
    df_clean["analise"] != "",
    "analise"
].value_counts()

email                22
quantidade            4
desconto              2
email; desconto       2
pedido_id ausente     1
preco_unitario        1
email; data           1
email; estado         1
Name: analise, dtype: int64

## 10. Criar campos derivados

Crie pelo menos uma coluna útil a partir dos dados limpos.

Sugestão:
- calcular `valor_bruto = quantidade × preco_unitario`;
- calcular `valor_liquido` aplicando `desconto_pct`.

**Funções/métodos úteis:**
- operações vetorizadas entre colunas;
- `.round()`

In [67]:
df_clean["valor_bruto"] = (
    df_clean["quantidade"] * df_clean["preco_unitario"]
)

df_clean["valor_liquido"] = (
    df_clean["valor_bruto"] * (1 - df_clean["desconto_pct"] / 100)
)

df_clean["valor_bruto"] = df_clean["valor_bruto"].round(2)
df_clean["valor_liquido"] = df_clean["valor_liquido"].round(2)

In [68]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 180 entries, 0 to 183
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pedido_id       179 non-null    object
 1   data_pedido     179 non-null    datetime64[ns]
 2   cliente         180 non-null    string
 3   email           170 non-null    string
 4   categoria       180 non-null    string
 5   produto         180 non-null    string
 6   quantidade      179 non-null    float64
 7   preco_unitario  179 non-null    float64
 8   desconto_pct    176 non-null    float64
 9   cidade          180 non-null    string
 10  estado          180 non-null    string
 11  status          180 non-null    string
 12  revisar         180 non-null    boolean
 13  analise         180 non-null    object
 14  valor_bruto     178 non-null    float64
 15  valor_liquido   174 non-null    float64
dtypes: boolean(1), datetime64[ns](1), float64(5), object(2), string(7)
memory usage: 22.9+ KB

In [69]:
df_clean.head(10)

,pedido_id,data_pedido,cliente,email,categoria,produto,quantidade,preco_unitario,desconto_pct,cidade,estado,status,revisar,analise,valor_bruto,valor_liquido
0,PED-1001,2026-05-18,Daniel Almeida,daniel.almeida@email.com,Acessórios,Suporte para notebook,2.0,99.0,0.0,Porto Alegre,RS,Pago,False,,198.0,198.00
1,PED-1002,2026-05-14,Renata Gomes,renata.gomes@email.com,Escritório,Caneta gel,2.0,8.5,0.0,Criciúma,SC,Pago,False,,17.0,17.00
2,PED-1003,2026-06-28,Juliana Barbosa,juliana.barbosa@email.com,Escritório,Caderno A5,4.0,24.9,0.0,Florianópolis,SC,Entregue,False,,99.6,99.60
3,PED-1004,2026-05-09,Bruno Dias,bruno.dias@email.com,Informática,Mouse sem fio,4.0,79.9,0.0,São Paulo,SP,Enviado,False,,319.6,319.60
4,NaN,2026-05-20,Eduardo Oliveira,eduardo.oliveira@email.com,Casa,Garrafa térmica,1.0,69.0,0.0,Florianópolis,SC,Enviado,True,pedido_id ausente;,69.0,69.00
5,PED-1006,2026-07-04,Sofia Almeida,sofia.almeida@email.com,Acessórios,Suporte para notebook,5.0,99.0,0.0,Porto Alegre,RS,Pago,False,,495.0,495.00
6,PED-1007,2026-05-17,Carla Santos,carla.santos@email.com,Casa,Garrafa térmica,5.0,69.0,0.0,Florianópolis,SC,Cancelado,False,,345.0,345.00
7,PED-1008,2026-07-20,Helena Pereira,helena.pereira@email.com,Escritório,Caderno A5,1.0,24.9,15.0,Tubarão,SC,Pago,False,,24.9,21.16
8,PED-1009,2026-07-22,Renata Lima,renata.lima@email.com,Casa,Garrafa térmica,6.0,69.0,15.0,Tubarão,SC,Pago,False,,414.0,351.90
9,PED-1010,2026-07-01,Ana Barbosa,ana.barbosa@email.com,Escritório,Caderno A5,0.0,24.9,5.0,Criciúma,SC,Enviado,True,quantidade;,0.0,0.00

## 11. Verificação final

Repita parte da auditoria inicial para demonstrar o efeito da limpeza.

Compare:
- linhas totais;
- duplicatas;
- valores ausentes;
- tipos;
- categorias;
- registros marcados para revisão.

O objetivo é mostrar evidência de melhoria, não apenas produzir um novo arquivo.

In [70]:
resumo_final = pd.DataFrame({
    "Métrica": [
        "Linhas finais",
        "Duplicatas restantes",
        "Datas inválidas/ausentes",
        "E-mails problemáticos",
        "Estados inválidos",
        "Quantidades problemáticas",
        "Preços problemáticos",
        "Descontos ausentes",
        "Categorias únicas",
        "Registros para revisão"
    ],
    "Resultado": [
        len(df_clean),
        df_clean.duplicated().sum(),
        df_clean["data_pedido"].isna().sum(),
        emails_problematicos.sum(),
        estados_problematicos.sum(),
        quantidades_problematicas.sum(),
        precos_problematicos.sum(),
        descontos_problematicos.sum(),
        df_clean["categoria"].nunique(),
        df_clean["revisar"].sum()
    ]
})

resumo_final

                     Métrica  Resultado
0              Linhas finais        180
1       Duplicatas restantes          0
2   Datas inválidas/ausentes          1
3      E-mails problemáticos         26
4          Estados inválidos          1
5  Quantidades problemáticas          4
6       Preços problemáticos          1
7         Descontos ausentes          4
8          Categorias únicas          4
9     Registros para revisão         34

In [71]:
motivos_revisao = (
    df_clean.loc[df_clean["revisar"], "analise"]
    .value_counts()
    .rename_axis("Motivo")
    .reset_index(name="Quantidade")
)

motivos_revisao

                Motivo  Quantidade
0              email;           22
1         quantidade;            4
2           desconto;            2
3    email; desconto;            2
4  pedido_id ausente;            1
5     preco_unitario;            1
6        email; data;            1
7      email; estado;            1

A limpeza removeu duplicatas exatas, padronizou campos textuais, converteu datas e valores numéricos, reduziu a coluna categoria de 15 representações para 4 categorias canônicas e sinalizou 33 registros para revisão manual. Valores ambíguos não foram corrigidos automaticamente.

In [72]:
def auditar_base(base):
    padrao_email = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

    emails_problematicos = (
        base["email"].isna()
        | ~base["email"].astype("string").str.strip().str.match(
            padrao_email, na=False
        )
    ).sum()

    return {
        "Linhas": len(base),
        "Duplicatas": base.duplicated().sum(),
        "E-mails problemáticos": emails_problematicos,
        "Categorias únicas": base["categoria"].nunique(),
    }

In [73]:
antes = auditar_base(df)
depois = auditar_base(df_clean)

comparacao = pd.DataFrame({
    "Métrica": antes.keys(),
    "Antes": antes.values(),
    "Depois": depois.values()
})

In [74]:
comparacao = pd.DataFrame({
    "Métrica": [
        "Linhas",
        "Duplicatas",
        "Categorias distintas",
        "Registros com data inválida",
        "E-mails problemáticos",
        "Registros para revisão"
    ],
    "Antes": [
        184,
        4,
        15,
        1,
        26,
        None
    ],
    "Depois": [
        180,
        0,
        4,
        1,
        26,
        33
    ]
})

In [75]:
comparacao["Resultado"] = [
    "4 duplicatas removidas",
    "Eliminadas",
    "15 → 4 categorias canônicas",
    "Detectada e sinalizada",
    "Detectados e sinalizados",
    "33 registros sinalizados"
]
comparacao

                       Métrica  Antes  Depois                    Resultado
0                       Linhas  184.0     180       4 duplicatas removidas
1                   Duplicatas    4.0       0                   Eliminadas
2         Categorias distintas   15.0       4  15 → 4 categorias canônicas
3  Registros com data inválida    1.0       1       Detectada e sinalizada
4        E-mails problemáticos   26.0      26     Detectados e sinalizados
5       Registros para revisão    NaN      33     33 registros sinalizados

## 12. Exportar a base limpa

Salve o resultado em `../data/processed/pedidos_limpos.xlsx`.

Se quiser, crie também uma segunda aba ou arquivo com os registros que ficaram marcados para revisão manual.

**Funções/métodos úteis:**
- `.to_excel()`
- `index=False`
- `pd.ExcelWriter()` caso queira múltiplas abas

In [76]:
with pd.ExcelWriter(
    "../data/processed/pedidos_limpos.xlsx",
    engine="xlsxwriter",
    datetime_format="dd/mm/yyyy",
    date_format="dd/mm/yyyy"
) as writer:
    df_clean.to_excel(
        writer,
        sheet_name="Pedidos",
        index=False
    )

## 13. Resumo do case

Ao terminar, registre em poucas linhas:
- principais problemas encontrados;
- transformações realizadas;
- anomalias que não foram corrigidas automaticamente;
- resultado final.

Esse resumo depois será reaproveitado no `README.md` e nas plataformas de freelance.